---
nextcloud_version: 11.0
mariadb_version: 10.1
nginx_version: 1.11

data_root_dir: /data
data_nextcloud_dir: /data/nextcloud
data_nextcloud_apps_dir: /data/nextcloud/apps
data_nextcloud_config_dir: /data/nextcloud/config
data_nextcloud_data_dir: /data/nextcloud/data
data_mysql_dir: /data/mysql
data_mysql_config_dir: /data/mysql/conf.d
data_mysql_data_dir: /data/mysql/data
data_nginx_dir: /data/nginx
data_nginx_config_dir: /data/nginx/conf.d
data_nginx_log_dir: /data/nginx/log
data_letsencrypt_dir: /data/letsencrypt
data_letsencrypt_build_dir: /data/letsencrypt/build
data_letsencrypt_certs_dir: /data/letsencrypt/certs
data_letsencrypt_webroot_dir: /data/letsencrypt/www

